# Generated by Django 4.0.2 on 2022-02-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomeclient',
            old_name='client',
            new_name='sotuvchi',
        ),
        migrations.RenameField(
            model_name='incomedehqon',
            old_name='client',
            new_name='dehqon',
        ),
    ]
