# Generated by Django 4.0.2 on 2022-02-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_client_incomeclient_sotuvchi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomesotuvchi',
            old_name='client',
            new_name='sotuvchi',
        ),
        migrations.RemoveField(
            model_name='incomeclient',
            name='sotuvchi',
        ),
        migrations.AddField(
            model_name='incomeclient',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qaysi client oldi+', to='app.client'),
        ),
        migrations.AddField(
            model_name='incomeclient',
            name='dehqon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qaysi dehqonni qoyi+', to='app.client'),
        ),
    ]
