# Generated by Django 4.0.2 on 2022-02-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_client_incomesotuvchi_sotuvchi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeclient',
            name='dehqon',
        ),
        migrations.RemoveField(
            model_name='incomeclient',
            name='product',
        ),
        migrations.AddField(
            model_name='expensedehqon',
            name='status',
            field=models.CharField(blank=True, choices=[('progress', 'Jarayonda'), ('compleated', 'Yakunlandi')], default='Jarayonda', max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='incomeclient',
            name='product_dehqon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qaysi dehqonni qoyi+', to='app.expensedehqon'),
        ),
        migrations.AddField(
            model_name='incomeclient',
            name='status',
            field=models.CharField(blank=True, choices=[('progress', 'Jarayonda'), ('compleated', 'Yakunlandi')], default='Jarayonda', max_length=125, null=True),
        ),
    ]
