# Generated by Django 4.0.2 on 2022-02-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_incomeclient_dehqon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeclient',
            name='status',
            field=models.CharField(blank=True, choices=[('progress', 'Jarayonda'), ('compleated', 'Yakunlandi')], default='progress', max_length=125, null=True),
        ),
    ]
