# Generated by Django 4.0.2 on 2022-02-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_incomeclient_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client')),
                ('income_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.incomeclient')),
            ],
        ),
        migrations.DeleteModel(
            name='ExpenseClienet',
        ),
    ]
