# Generated by Django 4.0.2 on 2022-02-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_expenseclient_delete_expenseclienet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedehqon',
            name='status',
            field=models.CharField(blank=True, choices=[('progress', 'Jarayonda'), ('compleated', 'Yakunlandi')], default='progress', max_length=125, null=True),
        ),
    ]
