# Generated by Django 4.0.2 on 2022-02-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_expensedehqon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseclient',
            name='income_client',
        ),
        migrations.AlterField(
            model_name='expenseclient',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.incomeclient'),
        ),
    ]
