# Generated by Django 4.0.2 on 2022-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_client_expenseclient_income_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeclient',
            name='status',
            field=models.CharField(blank=True, choices=[('progress', 'Jarayonda'), ('completed', 'Yakunlandi')], default='progress', max_length=125, null=True),
        ),
    ]
