# Generated by Django 4.0.2 on 2022-02-09 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_incomeclient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomedehqon',
            name='dehqon',
        ),
        migrations.AddField(
            model_name='incomedehqon',
            name='dehqon_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.expensedehqon'),
        ),
        migrations.AlterField(
            model_name='expensedehqon',
            name='status',
            field=models.CharField(blank=True, choices=[('progress', 'Jarayonda'), ('completed', 'Yakunlandi')], default='progress', max_length=125, null=True),
        ),
    ]
