# Generated by Django 4.0.2 on 2022-02-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_incomedehqon_dehqon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedehqon',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
