# Generated by Django 4.0.2 on 2022-02-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_teri_kallahasb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomeclient',
            old_name='created_date',
            new_name='bron_date',
        ),
        migrations.AlterField(
            model_name='expenseclient',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='status',
            field=models.CharField(blank=True, choices=[('bron', 'Bron qilindi'), ('progress', 'Jarayonda'), ('completed', 'Yakunlandi')], default='progress', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
