# Generated by Django 4.0.2 on 2022-02-12 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_created_date_incomeclient_bron_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeclient',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 3, 19, 20, 408365)),
        ),
    ]
