# Generated by Django 4.0.2 on 2022-02-12 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_incomeclient_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeclient',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
