# Generated by Django 4.0.2 on 2022-02-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_incomeclient_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeclient',
            name='bron_date',
        ),
        migrations.AlterField(
            model_name='incomeclient',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
