# Generated by Django 4.0.2 on 2022-02-12 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_incomeclient_bron_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeclient',
            name='created_date1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
