# Generated by Django 4.0.2 on 2022-02-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_incomeclient_created_date1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeclient',
            name='created_date1',
        ),
    ]
