# Generated by Django 4.0.2 on 2022-02-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_incomeclient_created_date1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=125, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('choise', models.CharField(blank=True, choices=[('qushxona', 'Qushxona uchun xarajat'), ('bozor', 'bozordagi xarajatlar')], max_length=125, null=True)),
            ],
        ),
    ]
