# Generated by Django 4.0.2 on 2022-02-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_xarajat'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status_bozor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
