# Generated by Django 4.0.2 on 2022-02-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_incomesotuvchi_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesotuvchi',
            name='client',
        ),
        migrations.RemoveField(
            model_name='expensesotuvchi',
            name='sotuvchi',
        ),
        migrations.AddField(
            model_name='expensesotuvchi',
            name='income_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sotuvchi', to='app.incomeclient'),
        ),
    ]
