# Generated by Django 4.0.2 on 2022-02-13 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_expensesotuvchi_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesotuvchi',
            name='income_client',
        ),
        migrations.AddField(
            model_name='expensesotuvchi',
            name='income_sotuvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.incomesotuvchi'),
        ),
    ]
